/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebCreateDictEntityRequest,
  WebDictEntity,
  WebErrorResponse,
  WebListDictEntitiesResponse,
  WebUpdateDictEntityRequest,
} from '../models/index';
import {
    WebCreateDictEntityRequestFromJSON,
    WebCreateDictEntityRequestToJSON,
    WebDictEntityFromJSON,
    WebDictEntityToJSON,
    WebErrorResponseFromJSON,
    WebErrorResponseToJSON,
    WebListDictEntitiesResponseFromJSON,
    WebListDictEntitiesResponseToJSON,
    WebUpdateDictEntityRequestFromJSON,
    WebUpdateDictEntityRequestToJSON,
} from '../models/index';

export interface ImpactsIdDeleteRequest {
    id: number;
}

export interface ImpactsIdGetRequest {
    id: number;
}

export interface ImpactsIdPutRequest {
    id: number;
    request: WebUpdateDictEntityRequest;
}

export interface ImpactsPostRequest {
    request: WebCreateDictEntityRequest;
}

/**
 * 
 */
export class ImpactsApi extends runtime.BaseAPI {

    /**
     * Creates request options for impactsGet without sending the request
     */
    async impactsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/impacts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all impacts in dictionary
     * List impacts
     */
    async impactsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebListDictEntitiesResponse>> {
        const requestOptions = await this.impactsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebListDictEntitiesResponseFromJSON(jsonValue));
    }

    /**
     * Get all impacts in dictionary
     * List impacts
     */
    async impactsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebListDictEntitiesResponse> {
        const response = await this.impactsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for impactsIdDelete without sending the request
     */
    async impactsIdDeleteRequestOpts(requestParameters: ImpactsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling impactsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/impacts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete impact dictionary entry by ID
     * Delete impact
     */
    async impactsIdDeleteRaw(requestParameters: ImpactsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.impactsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete impact dictionary entry by ID
     * Delete impact
     */
    async impactsIdDelete(requestParameters: ImpactsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.impactsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for impactsIdGet without sending the request
     */
    async impactsIdGetRequestOpts(requestParameters: ImpactsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling impactsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/impacts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get impact dictionary entry by ID
     * Get impact by ID
     */
    async impactsIdGetRaw(requestParameters: ImpactsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebDictEntity>> {
        const requestOptions = await this.impactsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebDictEntityFromJSON(jsonValue));
    }

    /**
     * Get impact dictionary entry by ID
     * Get impact by ID
     */
    async impactsIdGet(requestParameters: ImpactsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebDictEntity> {
        const response = await this.impactsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for impactsIdPut without sending the request
     */
    async impactsIdPutRequestOpts(requestParameters: ImpactsIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling impactsIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling impactsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/impacts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WebUpdateDictEntityRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update impact dictionary entry by ID
     * Update impact
     */
    async impactsIdPutRaw(requestParameters: ImpactsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebDictEntity>> {
        const requestOptions = await this.impactsIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebDictEntityFromJSON(jsonValue));
    }

    /**
     * Update impact dictionary entry by ID
     * Update impact
     */
    async impactsIdPut(requestParameters: ImpactsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebDictEntity> {
        const response = await this.impactsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for impactsPost without sending the request
     */
    async impactsPostRequestOpts(requestParameters: ImpactsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling impactsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/impacts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebCreateDictEntityRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create new impact dictionary entry
     * Create impact
     */
    async impactsPostRaw(requestParameters: ImpactsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebDictEntity>> {
        const requestOptions = await this.impactsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebDictEntityFromJSON(jsonValue));
    }

    /**
     * Create new impact dictionary entry
     * Create impact
     */
    async impactsPost(requestParameters: ImpactsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebDictEntity> {
        const response = await this.impactsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
