/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebCreateIncidentRequest,
  WebErrorResponse,
  WebIncidentComment,
  WebIncidentCommentCreateRequest,
  WebIncidentCommentListResponse,
  WebIncidentListResponse,
  WebIncidentResponse,
  WebUpdateIncidentRequest,
} from '../models/index';
import {
    WebCreateIncidentRequestFromJSON,
    WebCreateIncidentRequestToJSON,
    WebErrorResponseFromJSON,
    WebErrorResponseToJSON,
    WebIncidentCommentFromJSON,
    WebIncidentCommentToJSON,
    WebIncidentCommentCreateRequestFromJSON,
    WebIncidentCommentCreateRequestToJSON,
    WebIncidentCommentListResponseFromJSON,
    WebIncidentCommentListResponseToJSON,
    WebIncidentListResponseFromJSON,
    WebIncidentListResponseToJSON,
    WebIncidentResponseFromJSON,
    WebIncidentResponseToJSON,
    WebUpdateIncidentRequestFromJSON,
    WebUpdateIncidentRequestToJSON,
} from '../models/index';

export interface IncidentsGetRequest {
    statusIds?: Array<number>;
    priorityIds?: Array<number>;
    teamIds?: Array<number>;
    userIds?: Array<number>;
    authorIds?: Array<number>;
    limit?: number;
    offset?: number;
}

export interface IncidentsIdCommentsGetRequest {
    id: number;
    limit?: number;
    offset?: number;
}

export interface IncidentsIdCommentsPostRequest {
    id: number;
    request: WebIncidentCommentCreateRequest;
}

export interface IncidentsIdDeleteRequest {
    id: number;
}

export interface IncidentsIdGetRequest {
    id: number;
}

export interface IncidentsIdPatchRequest {
    id: number;
    request: WebUpdateIncidentRequest;
}

export interface IncidentsPostRequest {
    request: WebCreateIncidentRequest;
}

/**
 * 
 */
export class IncidentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for incidentsGet without sending the request
     */
    async incidentsGetRequestOpts(requestParameters: IncidentsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['statusIds'] != null) {
            queryParameters['statusIds'] = requestParameters['statusIds']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['priorityIds'] != null) {
            queryParameters['priorityIds'] = requestParameters['priorityIds']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['teamIds'] != null) {
            queryParameters['teamIds'] = requestParameters['teamIds']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['userIds'] != null) {
            queryParameters['userIds'] = requestParameters['userIds']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['authorIds'] != null) {
            queryParameters['authorIds'] = requestParameters['authorIds']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/incidents`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all incidents with pagination
     * List incidents
     */
    async incidentsGetRaw(requestParameters: IncidentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebIncidentListResponse>> {
        const requestOptions = await this.incidentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebIncidentListResponseFromJSON(jsonValue));
    }

    /**
     * Get all incidents with pagination
     * List incidents
     */
    async incidentsGet(requestParameters: IncidentsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebIncidentListResponse> {
        const response = await this.incidentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for incidentsIdCommentsGet without sending the request
     */
    async incidentsIdCommentsGetRequestOpts(requestParameters: IncidentsIdCommentsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling incidentsIdCommentsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/incidents/{id}/comments`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all comments for an incident with pagination
     * Get incident comments
     */
    async incidentsIdCommentsGetRaw(requestParameters: IncidentsIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebIncidentCommentListResponse>> {
        const requestOptions = await this.incidentsIdCommentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebIncidentCommentListResponseFromJSON(jsonValue));
    }

    /**
     * Get all comments for an incident with pagination
     * Get incident comments
     */
    async incidentsIdCommentsGet(requestParameters: IncidentsIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebIncidentCommentListResponse> {
        const response = await this.incidentsIdCommentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for incidentsIdCommentsPost without sending the request
     */
    async incidentsIdCommentsPostRequestOpts(requestParameters: IncidentsIdCommentsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling incidentsIdCommentsPost().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling incidentsIdCommentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/incidents/{id}/comments`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebIncidentCommentCreateRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create a new comment for an incident
     * Create incident comment
     */
    async incidentsIdCommentsPostRaw(requestParameters: IncidentsIdCommentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebIncidentComment>> {
        const requestOptions = await this.incidentsIdCommentsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebIncidentCommentFromJSON(jsonValue));
    }

    /**
     * Create a new comment for an incident
     * Create incident comment
     */
    async incidentsIdCommentsPost(requestParameters: IncidentsIdCommentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebIncidentComment> {
        const response = await this.incidentsIdCommentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for incidentsIdDelete without sending the request
     */
    async incidentsIdDeleteRequestOpts(requestParameters: IncidentsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling incidentsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/incidents/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete incident
     * Delete incident
     */
    async incidentsIdDeleteRaw(requestParameters: IncidentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.incidentsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete incident
     * Delete incident
     */
    async incidentsIdDelete(requestParameters: IncidentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incidentsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for incidentsIdGet without sending the request
     */
    async incidentsIdGetRequestOpts(requestParameters: IncidentsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling incidentsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/incidents/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get incident by ID
     * Get incident
     */
    async incidentsIdGetRaw(requestParameters: IncidentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebIncidentResponse>> {
        const requestOptions = await this.incidentsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebIncidentResponseFromJSON(jsonValue));
    }

    /**
     * Get incident by ID
     * Get incident
     */
    async incidentsIdGet(requestParameters: IncidentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebIncidentResponse> {
        const response = await this.incidentsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for incidentsIdPatch without sending the request
     */
    async incidentsIdPatchRequestOpts(requestParameters: IncidentsIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling incidentsIdPatch().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling incidentsIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/incidents/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: WebUpdateIncidentRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update incident
     * Update incident
     */
    async incidentsIdPatchRaw(requestParameters: IncidentsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebIncidentResponse>> {
        const requestOptions = await this.incidentsIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebIncidentResponseFromJSON(jsonValue));
    }

    /**
     * Update incident
     * Update incident
     */
    async incidentsIdPatch(requestParameters: IncidentsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebIncidentResponse> {
        const response = await this.incidentsIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for incidentsPost without sending the request
     */
    async incidentsPostRequestOpts(requestParameters: IncidentsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling incidentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/incidents`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebCreateIncidentRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create new incident
     * Create incident
     */
    async incidentsPostRaw(requestParameters: IncidentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebIncidentResponse>> {
        const requestOptions = await this.incidentsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebIncidentResponseFromJSON(jsonValue));
    }

    /**
     * Create new incident
     * Create incident
     */
    async incidentsPost(requestParameters: IncidentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebIncidentResponse> {
        const response = await this.incidentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
