/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebCreatePriorityRequest,
  WebErrorResponse,
  WebListPrioritiesResponse,
  WebPriority,
  WebUpdatePriorityRequest,
} from '../models/index';
import {
    WebCreatePriorityRequestFromJSON,
    WebCreatePriorityRequestToJSON,
    WebErrorResponseFromJSON,
    WebErrorResponseToJSON,
    WebListPrioritiesResponseFromJSON,
    WebListPrioritiesResponseToJSON,
    WebPriorityFromJSON,
    WebPriorityToJSON,
    WebUpdatePriorityRequestFromJSON,
    WebUpdatePriorityRequestToJSON,
} from '../models/index';

export interface PrioritiesIdDeleteRequest {
    id: number;
}

export interface PrioritiesIdGetRequest {
    id: number;
}

export interface PrioritiesIdPutRequest {
    id: number;
    request: WebUpdatePriorityRequest;
}

export interface PrioritiesPostRequest {
    request: WebCreatePriorityRequest;
}

/**
 * 
 */
export class PrioritiesApi extends runtime.BaseAPI {

    /**
     * Creates request options for prioritiesGet without sending the request
     */
    async prioritiesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/priorities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all priorities in dictionary
     * List priorities
     */
    async prioritiesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebListPrioritiesResponse>> {
        const requestOptions = await this.prioritiesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebListPrioritiesResponseFromJSON(jsonValue));
    }

    /**
     * Get all priorities in dictionary
     * List priorities
     */
    async prioritiesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebListPrioritiesResponse> {
        const response = await this.prioritiesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for prioritiesIdDelete without sending the request
     */
    async prioritiesIdDeleteRequestOpts(requestParameters: PrioritiesIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling prioritiesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/priorities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete priority dictionary entry by ID
     * Delete priority
     */
    async prioritiesIdDeleteRaw(requestParameters: PrioritiesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.prioritiesIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete priority dictionary entry by ID
     * Delete priority
     */
    async prioritiesIdDelete(requestParameters: PrioritiesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.prioritiesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for prioritiesIdGet without sending the request
     */
    async prioritiesIdGetRequestOpts(requestParameters: PrioritiesIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling prioritiesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/priorities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get priority dictionary entry by ID
     * Get priority by ID
     */
    async prioritiesIdGetRaw(requestParameters: PrioritiesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebPriority>> {
        const requestOptions = await this.prioritiesIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebPriorityFromJSON(jsonValue));
    }

    /**
     * Get priority dictionary entry by ID
     * Get priority by ID
     */
    async prioritiesIdGet(requestParameters: PrioritiesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebPriority> {
        const response = await this.prioritiesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for prioritiesIdPut without sending the request
     */
    async prioritiesIdPutRequestOpts(requestParameters: PrioritiesIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling prioritiesIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling prioritiesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/priorities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WebUpdatePriorityRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update priority dictionary entry by ID
     * Update priority
     */
    async prioritiesIdPutRaw(requestParameters: PrioritiesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebPriority>> {
        const requestOptions = await this.prioritiesIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebPriorityFromJSON(jsonValue));
    }

    /**
     * Update priority dictionary entry by ID
     * Update priority
     */
    async prioritiesIdPut(requestParameters: PrioritiesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebPriority> {
        const response = await this.prioritiesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for prioritiesPost without sending the request
     */
    async prioritiesPostRequestOpts(requestParameters: PrioritiesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling prioritiesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/priorities`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebCreatePriorityRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create new status dictionary entry
     * Create status
     */
    async prioritiesPostRaw(requestParameters: PrioritiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebPriority>> {
        const requestOptions = await this.prioritiesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebPriorityFromJSON(jsonValue));
    }

    /**
     * Create new status dictionary entry
     * Create status
     */
    async prioritiesPost(requestParameters: PrioritiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebPriority> {
        const response = await this.prioritiesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
