/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebErrorResponse,
  WebListRolesResponse,
} from '../models/index';
import {
    WebErrorResponseFromJSON,
    WebErrorResponseToJSON,
    WebListRolesResponseFromJSON,
    WebListRolesResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class RolesApi extends runtime.BaseAPI {

    /**
     * Creates request options for rolesGet without sending the request
     */
    async rolesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/roles`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all user roles
     * List roles
     */
    async rolesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebListRolesResponse>> {
        const requestOptions = await this.rolesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebListRolesResponseFromJSON(jsonValue));
    }

    /**
     * Get all user roles
     * List roles
     */
    async rolesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebListRolesResponse> {
        const response = await this.rolesGetRaw(initOverrides);
        return await response.value();
    }

}
