/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebCreateStatusRequest,
  WebErrorResponse,
  WebListStatusesResponse,
  WebStatus,
  WebUpdateStatusRequest,
} from '../models/index';
import {
    WebCreateStatusRequestFromJSON,
    WebCreateStatusRequestToJSON,
    WebErrorResponseFromJSON,
    WebErrorResponseToJSON,
    WebListStatusesResponseFromJSON,
    WebListStatusesResponseToJSON,
    WebStatusFromJSON,
    WebStatusToJSON,
    WebUpdateStatusRequestFromJSON,
    WebUpdateStatusRequestToJSON,
} from '../models/index';

export interface StatusesIdDeleteRequest {
    id: number;
}

export interface StatusesIdGetRequest {
    id: number;
}

export interface StatusesIdPutRequest {
    id: number;
    request: WebUpdateStatusRequest;
}

export interface StatusesPostRequest {
    request: WebCreateStatusRequest;
}

/**
 * 
 */
export class StatusesApi extends runtime.BaseAPI {

    /**
     * Creates request options for statusesGet without sending the request
     */
    async statusesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/statuses`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all statuses in dictionary
     * List statuses
     */
    async statusesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebListStatusesResponse>> {
        const requestOptions = await this.statusesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebListStatusesResponseFromJSON(jsonValue));
    }

    /**
     * Get all statuses in dictionary
     * List statuses
     */
    async statusesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebListStatusesResponse> {
        const response = await this.statusesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for statusesIdDelete without sending the request
     */
    async statusesIdDeleteRequestOpts(requestParameters: StatusesIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling statusesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/statuses/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete status dictionary entry by ID
     * Delete status
     */
    async statusesIdDeleteRaw(requestParameters: StatusesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.statusesIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete status dictionary entry by ID
     * Delete status
     */
    async statusesIdDelete(requestParameters: StatusesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.statusesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for statusesIdGet without sending the request
     */
    async statusesIdGetRequestOpts(requestParameters: StatusesIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling statusesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/statuses/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get status dictionary entry by ID
     * Get status by ID
     */
    async statusesIdGetRaw(requestParameters: StatusesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebStatus>> {
        const requestOptions = await this.statusesIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebStatusFromJSON(jsonValue));
    }

    /**
     * Get status dictionary entry by ID
     * Get status by ID
     */
    async statusesIdGet(requestParameters: StatusesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebStatus> {
        const response = await this.statusesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for statusesIdPut without sending the request
     */
    async statusesIdPutRequestOpts(requestParameters: StatusesIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling statusesIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling statusesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/statuses/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WebUpdateStatusRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update status dictionary entry by ID
     * Update status
     */
    async statusesIdPutRaw(requestParameters: StatusesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebStatus>> {
        const requestOptions = await this.statusesIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebStatusFromJSON(jsonValue));
    }

    /**
     * Update status dictionary entry by ID
     * Update status
     */
    async statusesIdPut(requestParameters: StatusesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebStatus> {
        const response = await this.statusesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for statusesPost without sending the request
     */
    async statusesPostRequestOpts(requestParameters: StatusesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling statusesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/statuses`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebCreateStatusRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create new status dictionary entry
     * Create status
     */
    async statusesPostRaw(requestParameters: StatusesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebStatus>> {
        const requestOptions = await this.statusesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebStatusFromJSON(jsonValue));
    }

    /**
     * Create new status dictionary entry
     * Create status
     */
    async statusesPost(requestParameters: StatusesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebStatus> {
        const response = await this.statusesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
