/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebCreateTeamRequest,
  WebErrorResponse,
  WebListTeamsResponse,
  WebTeam,
  WebUpdateTeamRequest,
} from '../models/index';
import {
    WebCreateTeamRequestFromJSON,
    WebCreateTeamRequestToJSON,
    WebErrorResponseFromJSON,
    WebErrorResponseToJSON,
    WebListTeamsResponseFromJSON,
    WebListTeamsResponseToJSON,
    WebTeamFromJSON,
    WebTeamToJSON,
    WebUpdateTeamRequestFromJSON,
    WebUpdateTeamRequestToJSON,
} from '../models/index';

export interface TeamsIdDeleteRequest {
    id: number;
}

export interface TeamsIdGetRequest {
    id: number;
}

export interface TeamsIdPutRequest {
    id: number;
    request: WebUpdateTeamRequest;
}

export interface TeamsPostRequest {
    request: WebCreateTeamRequest;
}

/**
 * 
 */
export class TeamsApi extends runtime.BaseAPI {

    /**
     * Creates request options for teamsGet without sending the request
     */
    async teamsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/teams`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all teams in dictionary
     * List teams
     */
    async teamsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebListTeamsResponse>> {
        const requestOptions = await this.teamsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebListTeamsResponseFromJSON(jsonValue));
    }

    /**
     * Get all teams in dictionary
     * List teams
     */
    async teamsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebListTeamsResponse> {
        const response = await this.teamsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teamsIdDelete without sending the request
     */
    async teamsIdDeleteRequestOpts(requestParameters: TeamsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling teamsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/teams/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete team dictionary entry by ID
     * Delete team
     */
    async teamsIdDeleteRaw(requestParameters: TeamsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.teamsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete team dictionary entry by ID
     * Delete team
     */
    async teamsIdDelete(requestParameters: TeamsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.teamsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for teamsIdGet without sending the request
     */
    async teamsIdGetRequestOpts(requestParameters: TeamsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling teamsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/teams/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get team dictionary entry by ID
     * Get team by ID
     */
    async teamsIdGetRaw(requestParameters: TeamsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebTeam>> {
        const requestOptions = await this.teamsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebTeamFromJSON(jsonValue));
    }

    /**
     * Get team dictionary entry by ID
     * Get team by ID
     */
    async teamsIdGet(requestParameters: TeamsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebTeam> {
        const response = await this.teamsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teamsIdPut without sending the request
     */
    async teamsIdPutRequestOpts(requestParameters: TeamsIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling teamsIdPut().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling teamsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/teams/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WebUpdateTeamRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Update team dictionary entry by ID
     * Update team
     */
    async teamsIdPutRaw(requestParameters: TeamsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebTeam>> {
        const requestOptions = await this.teamsIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebTeamFromJSON(jsonValue));
    }

    /**
     * Update team dictionary entry by ID
     * Update team
     */
    async teamsIdPut(requestParameters: TeamsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebTeam> {
        const response = await this.teamsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teamsPost without sending the request
     */
    async teamsPostRequestOpts(requestParameters: TeamsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling teamsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/teams`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebCreateTeamRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create new team dictionary entry
     * Create team
     */
    async teamsPostRaw(requestParameters: TeamsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebTeam>> {
        const requestOptions = await this.teamsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebTeamFromJSON(jsonValue));
    }

    /**
     * Create new team dictionary entry
     * Create team
     */
    async teamsPost(requestParameters: TeamsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebTeam> {
        const response = await this.teamsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
