/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebAuthLoginRequest
 */
export interface WebAuthLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof WebAuthLoginRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof WebAuthLoginRequest
     */
    username: string;
}

/**
 * Check if a given object implements the WebAuthLoginRequest interface.
 */
export function instanceOfWebAuthLoginRequest(value: object): value is WebAuthLoginRequest {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function WebAuthLoginRequestFromJSON(json: any): WebAuthLoginRequest {
    return WebAuthLoginRequestFromJSONTyped(json, false);
}

export function WebAuthLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebAuthLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'username': json['username'],
    };
}

export function WebAuthLoginRequestToJSON(json: any): WebAuthLoginRequest {
    return WebAuthLoginRequestToJSONTyped(json, false);
}

export function WebAuthLoginRequestToJSONTyped(value?: WebAuthLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'username': value['username'],
    };
}

