/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebCreateUserRequest
 */
export interface WebCreateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof WebCreateUserRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof WebCreateUserRequest
     */
    password?: string;
    /**
     * 
     * @type {WebCreateUserRequestRoleEnum}
     * @memberof WebCreateUserRequest
     */
    role?: WebCreateUserRequestRoleEnum;
    /**
     * 
     * @type {number}
     * @memberof WebCreateUserRequest
     */
    teamId?: number;
    /**
     * 
     * @type {string}
     * @memberof WebCreateUserRequest
     */
    username?: string;
}


/**
 * @export
 */
export const WebCreateUserRequestRoleEnum = {
    Admin: 'admin',
    Manager: 'manager',
    User: 'user'
} as const;
export type WebCreateUserRequestRoleEnum = typeof WebCreateUserRequestRoleEnum[keyof typeof WebCreateUserRequestRoleEnum];


/**
 * Check if a given object implements the WebCreateUserRequest interface.
 */
export function instanceOfWebCreateUserRequest(value: object): value is WebCreateUserRequest {
    return true;
}

export function WebCreateUserRequestFromJSON(json: any): WebCreateUserRequest {
    return WebCreateUserRequestFromJSONTyped(json, false);
}

export function WebCreateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebCreateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'role': json['role'] == null ? undefined : json['role'],
        'teamId': json['teamId'] == null ? undefined : json['teamId'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function WebCreateUserRequestToJSON(json: any): WebCreateUserRequest {
    return WebCreateUserRequestToJSONTyped(json, false);
}

export function WebCreateUserRequestToJSONTyped(value?: WebCreateUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'role': value['role'],
        'teamId': value['teamId'],
        'username': value['username'],
    };
}

