/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebCreateDictEntityRequest
 */
export interface WebCreateDictEntityRequest {
    /**
     * 
     * @type {string}
     * @memberof WebCreateDictEntityRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof WebCreateDictEntityRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof WebCreateDictEntityRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WebCreateDictEntityRequest
     */
    sort: number;
}

/**
 * Check if a given object implements the WebCreateDictEntityRequest interface.
 */
export function instanceOfWebCreateDictEntityRequest(value: object): value is WebCreateDictEntityRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function WebCreateDictEntityRequestFromJSON(json: any): WebCreateDictEntityRequest {
    return WebCreateDictEntityRequestFromJSONTyped(json, false);
}

export function WebCreateDictEntityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebCreateDictEntityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
        'name': json['name'],
        'sort': json['sort'],
    };
}

export function WebCreateDictEntityRequestToJSON(json: any): WebCreateDictEntityRequest {
    return WebCreateDictEntityRequestToJSONTyped(json, false);
}

export function WebCreateDictEntityRequestToJSONTyped(value?: WebCreateDictEntityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'name': value['name'],
        'sort': value['sort'],
    };
}

