/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebChangePasswordRequest
 */
export interface WebChangePasswordRequest {
    /**
     * текущий пароль
     * @type {string}
     * @memberof WebChangePasswordRequest
     */
    currentPassword: string;
    /**
     * новый пароль
     * @type {string}
     * @memberof WebChangePasswordRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the WebChangePasswordRequest interface.
 */
export function instanceOfWebChangePasswordRequest(value: object): value is WebChangePasswordRequest {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function WebChangePasswordRequestFromJSON(json: any): WebChangePasswordRequest {
    return WebChangePasswordRequestFromJSONTyped(json, false);
}

export function WebChangePasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebChangePasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['currentPassword'],
        'newPassword': json['newPassword'],
    };
}

export function WebChangePasswordRequestToJSON(json: any): WebChangePasswordRequest {
    return WebChangePasswordRequestToJSONTyped(json, false);
}

export function WebChangePasswordRequestToJSONTyped(value?: WebChangePasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPassword': value['currentPassword'],
        'newPassword': value['newPassword'],
    };
}

