/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebCreateTeamRequest
 */
export interface WebCreateTeamRequest {
    /**
     * 
     * @type {string}
     * @memberof WebCreateTeamRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof WebCreateTeamRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof WebCreateTeamRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WebCreateTeamRequest
     */
    sort: number;
}

/**
 * Check if a given object implements the WebCreateTeamRequest interface.
 */
export function instanceOfWebCreateTeamRequest(value: object): value is WebCreateTeamRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function WebCreateTeamRequestFromJSON(json: any): WebCreateTeamRequest {
    return WebCreateTeamRequestFromJSONTyped(json, false);
}

export function WebCreateTeamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebCreateTeamRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
        'name': json['name'],
        'sort': json['sort'],
    };
}

export function WebCreateTeamRequestToJSON(json: any): WebCreateTeamRequest {
    return WebCreateTeamRequestToJSONTyped(json, false);
}

export function WebCreateTeamRequestToJSONTyped(value?: WebCreateTeamRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'name': value['name'],
        'sort': value['sort'],
    };
}

