/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebCreateStatusRequest
 */
export interface WebCreateStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof WebCreateStatusRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof WebCreateStatusRequest
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebCreateStatusRequest
     */
    isFinal: boolean;
    /**
     * 
     * @type {string}
     * @memberof WebCreateStatusRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WebCreateStatusRequest
     */
    sort: number;
}

/**
 * Check if a given object implements the WebCreateStatusRequest interface.
 */
export function instanceOfWebCreateStatusRequest(value: object): value is WebCreateStatusRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('isFinal' in value) || value['isFinal'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function WebCreateStatusRequestFromJSON(json: any): WebCreateStatusRequest {
    return WebCreateStatusRequestFromJSONTyped(json, false);
}

export function WebCreateStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebCreateStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
        'isFinal': json['isFinal'],
        'name': json['name'],
        'sort': json['sort'],
    };
}

export function WebCreateStatusRequestToJSON(json: any): WebCreateStatusRequest {
    return WebCreateStatusRequestToJSONTyped(json, false);
}

export function WebCreateStatusRequestToJSONTyped(value?: WebCreateStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'isFinal': value['isFinal'],
        'name': value['name'],
        'sort': value['sort'],
    };
}

