/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebCreateIncidentRequest
 */
export interface WebCreateIncidentRequest {
    /**
     * 
     * @type {number}
     * @memberof WebCreateIncidentRequest
     */
    authorId?: number;
    /**
     * 
     * @type {string}
     * @memberof WebCreateIncidentRequest
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof WebCreateIncidentRequest
     */
    priorityId: number;
    /**
     * 
     * @type {number}
     * @memberof WebCreateIncidentRequest
     */
    statusId: number;
    /**
     * 
     * @type {number}
     * @memberof WebCreateIncidentRequest
     */
    teamId?: number;
    /**
     * 
     * @type {string}
     * @memberof WebCreateIncidentRequest
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof WebCreateIncidentRequest
     */
    userId?: number;
}

/**
 * Check if a given object implements the WebCreateIncidentRequest interface.
 */
export function instanceOfWebCreateIncidentRequest(value: object): value is WebCreateIncidentRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('priorityId' in value) || value['priorityId'] === undefined) return false;
    if (!('statusId' in value) || value['statusId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function WebCreateIncidentRequestFromJSON(json: any): WebCreateIncidentRequest {
    return WebCreateIncidentRequestFromJSONTyped(json, false);
}

export function WebCreateIncidentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebCreateIncidentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'description': json['description'],
        'priorityId': json['priorityId'],
        'statusId': json['statusId'],
        'teamId': json['teamId'] == null ? undefined : json['teamId'],
        'title': json['title'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function WebCreateIncidentRequestToJSON(json: any): WebCreateIncidentRequest {
    return WebCreateIncidentRequestToJSONTyped(json, false);
}

export function WebCreateIncidentRequestToJSONTyped(value?: WebCreateIncidentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorId': value['authorId'],
        'description': value['description'],
        'priorityId': value['priorityId'],
        'statusId': value['statusId'],
        'teamId': value['teamId'],
        'title': value['title'],
        'userId': value['userId'],
    };
}

