/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebCreateIncidentRequest
 */
export interface WebCreateIncidentRequest {
    /**
     * 
     * @type {string}
     * @memberof WebCreateIncidentRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof WebCreateIncidentRequest
     */
    priorityId?: number;
    /**
     * 
     * @type {number}
     * @memberof WebCreateIncidentRequest
     */
    statusId?: number;
    /**
     * 
     * @type {string}
     * @memberof WebCreateIncidentRequest
     */
    title?: string;
}

/**
 * Check if a given object implements the WebCreateIncidentRequest interface.
 */
export function instanceOfWebCreateIncidentRequest(value: object): value is WebCreateIncidentRequest {
    return true;
}

export function WebCreateIncidentRequestFromJSON(json: any): WebCreateIncidentRequest {
    return WebCreateIncidentRequestFromJSONTyped(json, false);
}

export function WebCreateIncidentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebCreateIncidentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'priorityId': json['priorityId'] == null ? undefined : json['priorityId'],
        'statusId': json['statusId'] == null ? undefined : json['statusId'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function WebCreateIncidentRequestToJSON(json: any): WebCreateIncidentRequest {
    return WebCreateIncidentRequestToJSONTyped(json, false);
}

export function WebCreateIncidentRequestToJSONTyped(value?: WebCreateIncidentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'priorityId': value['priorityId'],
        'statusId': value['statusId'],
        'title': value['title'],
    };
}

