/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebDictEntity
 */
export interface WebDictEntity {
    /**
     * 
     * @type {string}
     * @memberof WebDictEntity
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof WebDictEntity
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof WebDictEntity
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WebDictEntity
     */
    name?: string;
}

/**
 * Check if a given object implements the WebDictEntity interface.
 */
export function instanceOfWebDictEntity(value: object): value is WebDictEntity {
    return true;
}

export function WebDictEntityFromJSON(json: any): WebDictEntity {
    return WebDictEntityFromJSONTyped(json, false);
}

export function WebDictEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebDictEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function WebDictEntityToJSON(json: any): WebDictEntity {
    return WebDictEntityToJSONTyped(json, false);
}

export function WebDictEntityToJSONTyped(value?: WebDictEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
    };
}

