/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebDictEntityShort
 */
export interface WebDictEntityShort {
    /**
     * 
     * @type {string}
     * @memberof WebDictEntityShort
     */
    code: string;
    /**
     * 
     * @type {number}
     * @memberof WebDictEntityShort
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof WebDictEntityShort
     */
    name: string;
}

/**
 * Check if a given object implements the WebDictEntityShort interface.
 */
export function instanceOfWebDictEntityShort(value: object): value is WebDictEntityShort {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WebDictEntityShortFromJSON(json: any): WebDictEntityShort {
    return WebDictEntityShortFromJSONTyped(json, false);
}

export function WebDictEntityShortFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebDictEntityShort {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'id': json['id'],
        'name': json['name'],
    };
}

export function WebDictEntityShortToJSON(json: any): WebDictEntityShort {
    return WebDictEntityShortToJSONTyped(json, false);
}

export function WebDictEntityShortToJSONTyped(value?: WebDictEntityShort | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'id': value['id'],
        'name': value['name'],
    };
}

