/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebErrorResponse
 */
export interface WebErrorResponse {
    /**
     * причина ошибки
     * @type {string}
     * @memberof WebErrorResponse
     */
    error: string;
    /**
     * сообщение, которое нужно показать пользователю
     * @type {string}
     * @memberof WebErrorResponse
     */
    userMessage: string;
}

/**
 * Check if a given object implements the WebErrorResponse interface.
 */
export function instanceOfWebErrorResponse(value: object): value is WebErrorResponse {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('userMessage' in value) || value['userMessage'] === undefined) return false;
    return true;
}

export function WebErrorResponseFromJSON(json: any): WebErrorResponse {
    return WebErrorResponseFromJSONTyped(json, false);
}

export function WebErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'userMessage': json['userMessage'],
    };
}

export function WebErrorResponseToJSON(json: any): WebErrorResponse {
    return WebErrorResponseToJSONTyped(json, false);
}

export function WebErrorResponseToJSONTyped(value?: WebErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'userMessage': value['userMessage'],
    };
}

