/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebIncidentComment } from './WebIncidentComment';
import {
    WebIncidentCommentFromJSON,
    WebIncidentCommentFromJSONTyped,
    WebIncidentCommentToJSON,
    WebIncidentCommentToJSONTyped,
} from './WebIncidentComment';
import type { WebPagination } from './WebPagination';
import {
    WebPaginationFromJSON,
    WebPaginationFromJSONTyped,
    WebPaginationToJSON,
    WebPaginationToJSONTyped,
} from './WebPagination';

/**
 * 
 * @export
 * @interface WebIncidentCommentListResponse
 */
export interface WebIncidentCommentListResponse {
    /**
     * 
     * @type {Array<WebIncidentComment>}
     * @memberof WebIncidentCommentListResponse
     */
    items: Array<WebIncidentComment>;
    /**
     * 
     * @type {WebPagination}
     * @memberof WebIncidentCommentListResponse
     */
    pagination: WebPagination;
}

/**
 * Check if a given object implements the WebIncidentCommentListResponse interface.
 */
export function instanceOfWebIncidentCommentListResponse(value: object): value is WebIncidentCommentListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function WebIncidentCommentListResponseFromJSON(json: any): WebIncidentCommentListResponse {
    return WebIncidentCommentListResponseFromJSONTyped(json, false);
}

export function WebIncidentCommentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebIncidentCommentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WebIncidentCommentFromJSON)),
        'pagination': WebPaginationFromJSON(json['pagination']),
    };
}

export function WebIncidentCommentListResponseToJSON(json: any): WebIncidentCommentListResponse {
    return WebIncidentCommentListResponseToJSONTyped(json, false);
}

export function WebIncidentCommentListResponseToJSONTyped(value?: WebIncidentCommentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WebIncidentCommentToJSON)),
        'pagination': WebPaginationToJSON(value['pagination']),
    };
}

