/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebIncidentCommentCreateRequest
 */
export interface WebIncidentCommentCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof WebIncidentCommentCreateRequest
     */
    text: string;
}

/**
 * Check if a given object implements the WebIncidentCommentCreateRequest interface.
 */
export function instanceOfWebIncidentCommentCreateRequest(value: object): value is WebIncidentCommentCreateRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function WebIncidentCommentCreateRequestFromJSON(json: any): WebIncidentCommentCreateRequest {
    return WebIncidentCommentCreateRequestFromJSONTyped(json, false);
}

export function WebIncidentCommentCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebIncidentCommentCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function WebIncidentCommentCreateRequestToJSON(json: any): WebIncidentCommentCreateRequest {
    return WebIncidentCommentCreateRequestToJSONTyped(json, false);
}

export function WebIncidentCommentCreateRequestToJSONTyped(value?: WebIncidentCommentCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

