/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebIncidentResponse } from './WebIncidentResponse';
import {
    WebIncidentResponseFromJSON,
    WebIncidentResponseFromJSONTyped,
    WebIncidentResponseToJSON,
    WebIncidentResponseToJSONTyped,
} from './WebIncidentResponse';
import type { WebPagination } from './WebPagination';
import {
    WebPaginationFromJSON,
    WebPaginationFromJSONTyped,
    WebPaginationToJSON,
    WebPaginationToJSONTyped,
} from './WebPagination';

/**
 * 
 * @export
 * @interface WebIncidentListResponse
 */
export interface WebIncidentListResponse {
    /**
     * 
     * @type {Array<WebIncidentResponse>}
     * @memberof WebIncidentListResponse
     */
    items: Array<WebIncidentResponse>;
    /**
     * 
     * @type {WebPagination}
     * @memberof WebIncidentListResponse
     */
    pagination: WebPagination;
}

/**
 * Check if a given object implements the WebIncidentListResponse interface.
 */
export function instanceOfWebIncidentListResponse(value: object): value is WebIncidentListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function WebIncidentListResponseFromJSON(json: any): WebIncidentListResponse {
    return WebIncidentListResponseFromJSONTyped(json, false);
}

export function WebIncidentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebIncidentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WebIncidentResponseFromJSON)),
        'pagination': WebPaginationFromJSON(json['pagination']),
    };
}

export function WebIncidentListResponseToJSON(json: any): WebIncidentListResponse {
    return WebIncidentListResponseToJSONTyped(json, false);
}

export function WebIncidentListResponseToJSONTyped(value?: WebIncidentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WebIncidentResponseToJSON)),
        'pagination': WebPaginationToJSON(value['pagination']),
    };
}

