/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebDictEntityShort } from './WebDictEntityShort';
import {
    WebDictEntityShortFromJSON,
    WebDictEntityShortFromJSONTyped,
    WebDictEntityShortToJSON,
    WebDictEntityShortToJSONTyped,
} from './WebDictEntityShort';
import type { WebUserResponse } from './WebUserResponse';
import {
    WebUserResponseFromJSON,
    WebUserResponseFromJSONTyped,
    WebUserResponseToJSON,
    WebUserResponseToJSONTyped,
} from './WebUserResponse';

/**
 * 
 * @export
 * @interface WebIncidentResponse
 */
export interface WebIncidentResponse {
    /**
     * 
     * @type {WebUserResponse}
     * @memberof WebIncidentResponse
     */
    author?: WebUserResponse;
    /**
     * 
     * @type {string}
     * @memberof WebIncidentResponse
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof WebIncidentResponse
     */
    id?: number;
    /**
     * 
     * @type {WebDictEntityShort}
     * @memberof WebIncidentResponse
     */
    priority?: WebDictEntityShort;
    /**
     * 
     * @type {WebDictEntityShort}
     * @memberof WebIncidentResponse
     */
    status?: WebDictEntityShort;
    /**
     * 
     * @type {WebDictEntityShort}
     * @memberof WebIncidentResponse
     */
    team?: WebDictEntityShort;
    /**
     * 
     * @type {string}
     * @memberof WebIncidentResponse
     */
    title?: string;
    /**
     * 
     * @type {WebUserResponse}
     * @memberof WebIncidentResponse
     */
    user?: WebUserResponse;
}

/**
 * Check if a given object implements the WebIncidentResponse interface.
 */
export function instanceOfWebIncidentResponse(value: object): value is WebIncidentResponse {
    return true;
}

export function WebIncidentResponseFromJSON(json: any): WebIncidentResponse {
    return WebIncidentResponseFromJSONTyped(json, false);
}

export function WebIncidentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebIncidentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'] == null ? undefined : WebUserResponseFromJSON(json['author']),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'priority': json['priority'] == null ? undefined : WebDictEntityShortFromJSON(json['priority']),
        'status': json['status'] == null ? undefined : WebDictEntityShortFromJSON(json['status']),
        'team': json['team'] == null ? undefined : WebDictEntityShortFromJSON(json['team']),
        'title': json['title'] == null ? undefined : json['title'],
        'user': json['user'] == null ? undefined : WebUserResponseFromJSON(json['user']),
    };
}

export function WebIncidentResponseToJSON(json: any): WebIncidentResponse {
    return WebIncidentResponseToJSONTyped(json, false);
}

export function WebIncidentResponseToJSONTyped(value?: WebIncidentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author': WebUserResponseToJSON(value['author']),
        'description': value['description'],
        'id': value['id'],
        'priority': WebDictEntityShortToJSON(value['priority']),
        'status': WebDictEntityShortToJSON(value['status']),
        'team': WebDictEntityShortToJSON(value['team']),
        'title': value['title'],
        'user': WebUserResponseToJSON(value['user']),
    };
}

