/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebUserResponse } from './WebUserResponse';
import {
    WebUserResponseFromJSON,
    WebUserResponseFromJSONTyped,
    WebUserResponseToJSON,
    WebUserResponseToJSONTyped,
} from './WebUserResponse';

/**
 * 
 * @export
 * @interface WebIncidentComment
 */
export interface WebIncidentComment {
    /**
     * 
     * @type {WebUserResponse}
     * @memberof WebIncidentComment
     */
    author: WebUserResponse;
    /**
     * 
     * @type {string}
     * @memberof WebIncidentComment
     */
    createdAt: string;
    /**
     * 
     * @type {number}
     * @memberof WebIncidentComment
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof WebIncidentComment
     */
    incidentId: number;
    /**
     * 
     * @type {string}
     * @memberof WebIncidentComment
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof WebIncidentComment
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the WebIncidentComment interface.
 */
export function instanceOfWebIncidentComment(value: object): value is WebIncidentComment {
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('incidentId' in value) || value['incidentId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WebIncidentCommentFromJSON(json: any): WebIncidentComment {
    return WebIncidentCommentFromJSONTyped(json, false);
}

export function WebIncidentCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebIncidentComment {
    if (json == null) {
        return json;
    }
    return {
        
        'author': WebUserResponseFromJSON(json['author']),
        'createdAt': json['createdAt'],
        'id': json['id'],
        'incidentId': json['incidentId'],
        'text': json['text'],
        'updatedAt': json['updatedAt'],
    };
}

export function WebIncidentCommentToJSON(json: any): WebIncidentComment {
    return WebIncidentCommentToJSONTyped(json, false);
}

export function WebIncidentCommentToJSONTyped(value?: WebIncidentComment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author': WebUserResponseToJSON(value['author']),
        'createdAt': value['createdAt'],
        'id': value['id'],
        'incidentId': value['incidentId'],
        'text': value['text'],
        'updatedAt': value['updatedAt'],
    };
}

