/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebPriority } from './WebPriority';
import {
    WebPriorityFromJSON,
    WebPriorityFromJSONTyped,
    WebPriorityToJSON,
    WebPriorityToJSONTyped,
} from './WebPriority';

/**
 * 
 * @export
 * @interface WebListPrioritiesResponse
 */
export interface WebListPrioritiesResponse {
    /**
     * 
     * @type {Array<WebPriority>}
     * @memberof WebListPrioritiesResponse
     */
    items: Array<WebPriority>;
}

/**
 * Check if a given object implements the WebListPrioritiesResponse interface.
 */
export function instanceOfWebListPrioritiesResponse(value: object): value is WebListPrioritiesResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function WebListPrioritiesResponseFromJSON(json: any): WebListPrioritiesResponse {
    return WebListPrioritiesResponseFromJSONTyped(json, false);
}

export function WebListPrioritiesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebListPrioritiesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WebPriorityFromJSON)),
    };
}

export function WebListPrioritiesResponseToJSON(json: any): WebListPrioritiesResponse {
    return WebListPrioritiesResponseToJSONTyped(json, false);
}

export function WebListPrioritiesResponseToJSONTyped(value?: WebListPrioritiesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WebPriorityToJSON)),
    };
}

