/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebUserResponse } from './WebUserResponse';
import {
    WebUserResponseFromJSON,
    WebUserResponseFromJSONTyped,
    WebUserResponseToJSON,
    WebUserResponseToJSONTyped,
} from './WebUserResponse';

/**
 * 
 * @export
 * @interface WebListUsersResponse
 */
export interface WebListUsersResponse {
    /**
     * 
     * @type {Array<WebUserResponse>}
     * @memberof WebListUsersResponse
     */
    items: Array<WebUserResponse>;
}

/**
 * Check if a given object implements the WebListUsersResponse interface.
 */
export function instanceOfWebListUsersResponse(value: object): value is WebListUsersResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function WebListUsersResponseFromJSON(json: any): WebListUsersResponse {
    return WebListUsersResponseFromJSONTyped(json, false);
}

export function WebListUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebListUsersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WebUserResponseFromJSON)),
    };
}

export function WebListUsersResponseToJSON(json: any): WebListUsersResponse {
    return WebListUsersResponseToJSONTyped(json, false);
}

export function WebListUsersResponseToJSONTyped(value?: WebListUsersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WebUserResponseToJSON)),
    };
}

