/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebTeam } from './WebTeam';
import {
    WebTeamFromJSON,
    WebTeamFromJSONTyped,
    WebTeamToJSON,
    WebTeamToJSONTyped,
} from './WebTeam';

/**
 * 
 * @export
 * @interface WebListTeamsResponse
 */
export interface WebListTeamsResponse {
    /**
     * 
     * @type {Array<WebTeam>}
     * @memberof WebListTeamsResponse
     */
    items: Array<WebTeam>;
}

/**
 * Check if a given object implements the WebListTeamsResponse interface.
 */
export function instanceOfWebListTeamsResponse(value: object): value is WebListTeamsResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function WebListTeamsResponseFromJSON(json: any): WebListTeamsResponse {
    return WebListTeamsResponseFromJSONTyped(json, false);
}

export function WebListTeamsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebListTeamsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WebTeamFromJSON)),
    };
}

export function WebListTeamsResponseToJSON(json: any): WebListTeamsResponse {
    return WebListTeamsResponseToJSONTyped(json, false);
}

export function WebListTeamsResponseToJSONTyped(value?: WebListTeamsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WebTeamToJSON)),
    };
}

