/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebStatus } from './WebStatus';
import {
    WebStatusFromJSON,
    WebStatusFromJSONTyped,
    WebStatusToJSON,
    WebStatusToJSONTyped,
} from './WebStatus';

/**
 * 
 * @export
 * @interface WebListStatusesResponse
 */
export interface WebListStatusesResponse {
    /**
     * 
     * @type {Array<WebStatus>}
     * @memberof WebListStatusesResponse
     */
    items: Array<WebStatus>;
}

/**
 * Check if a given object implements the WebListStatusesResponse interface.
 */
export function instanceOfWebListStatusesResponse(value: object): value is WebListStatusesResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function WebListStatusesResponseFromJSON(json: any): WebListStatusesResponse {
    return WebListStatusesResponseFromJSONTyped(json, false);
}

export function WebListStatusesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebListStatusesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WebStatusFromJSON)),
    };
}

export function WebListStatusesResponseToJSON(json: any): WebListStatusesResponse {
    return WebListStatusesResponseToJSONTyped(json, false);
}

export function WebListStatusesResponseToJSONTyped(value?: WebListStatusesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WebStatusToJSON)),
    };
}

