/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebDictEntity } from './WebDictEntity';
import {
    WebDictEntityFromJSON,
    WebDictEntityFromJSONTyped,
    WebDictEntityToJSON,
    WebDictEntityToJSONTyped,
} from './WebDictEntity';

/**
 * 
 * @export
 * @interface WebListDictEntitiesResponse
 */
export interface WebListDictEntitiesResponse {
    /**
     * 
     * @type {Array<WebDictEntity>}
     * @memberof WebListDictEntitiesResponse
     */
    items: Array<WebDictEntity>;
}

/**
 * Check if a given object implements the WebListDictEntitiesResponse interface.
 */
export function instanceOfWebListDictEntitiesResponse(value: object): value is WebListDictEntitiesResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function WebListDictEntitiesResponseFromJSON(json: any): WebListDictEntitiesResponse {
    return WebListDictEntitiesResponseFromJSONTyped(json, false);
}

export function WebListDictEntitiesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebListDictEntitiesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WebDictEntityFromJSON)),
    };
}

export function WebListDictEntitiesResponseToJSON(json: any): WebListDictEntitiesResponse {
    return WebListDictEntitiesResponseToJSONTyped(json, false);
}

export function WebListDictEntitiesResponseToJSONTyped(value?: WebListDictEntitiesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WebDictEntityToJSON)),
    };
}

