/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebRole } from './WebRole';
import {
    WebRoleFromJSON,
    WebRoleFromJSONTyped,
    WebRoleToJSON,
    WebRoleToJSONTyped,
} from './WebRole';

/**
 * 
 * @export
 * @interface WebListRolesResponse
 */
export interface WebListRolesResponse {
    /**
     * 
     * @type {Array<WebRole>}
     * @memberof WebListRolesResponse
     */
    items: Array<WebRole>;
}

/**
 * Check if a given object implements the WebListRolesResponse interface.
 */
export function instanceOfWebListRolesResponse(value: object): value is WebListRolesResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function WebListRolesResponseFromJSON(json: any): WebListRolesResponse {
    return WebListRolesResponseFromJSONTyped(json, false);
}

export function WebListRolesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebListRolesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WebRoleFromJSON)),
    };
}

export function WebListRolesResponseToJSON(json: any): WebListRolesResponse {
    return WebListRolesResponseToJSONTyped(json, false);
}

export function WebListRolesResponseToJSONTyped(value?: WebListRolesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WebRoleToJSON)),
    };
}

