/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebPriority
 */
export interface WebPriority {
    /**
     * 
     * @type {string}
     * @memberof WebPriority
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof WebPriority
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof WebPriority
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof WebPriority
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WebPriority
     */
    sort: number;
}

/**
 * Check if a given object implements the WebPriority interface.
 */
export function instanceOfWebPriority(value: object): value is WebPriority {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function WebPriorityFromJSON(json: any): WebPriority {
    return WebPriorityFromJSONTyped(json, false);
}

export function WebPriorityFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebPriority {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
        'id': json['id'],
        'name': json['name'],
        'sort': json['sort'],
    };
}

export function WebPriorityToJSON(json: any): WebPriority {
    return WebPriorityToJSONTyped(json, false);
}

export function WebPriorityToJSONTyped(value?: WebPriority | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'sort': value['sort'],
    };
}

