/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebPermission
 */
export interface WebPermission {
    /**
     * 
     * @type {string}
     * @memberof WebPermission
     */
    code: string;
}

/**
 * Check if a given object implements the WebPermission interface.
 */
export function instanceOfWebPermission(value: object): value is WebPermission {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function WebPermissionFromJSON(json: any): WebPermission {
    return WebPermissionFromJSONTyped(json, false);
}

export function WebPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebPermission {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function WebPermissionToJSON(json: any): WebPermission {
    return WebPermissionToJSONTyped(json, false);
}

export function WebPermissionToJSONTyped(value?: WebPermission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

