/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebPagination
 */
export interface WebPagination {
    /**
     * 
     * @type {number}
     * @memberof WebPagination
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof WebPagination
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof WebPagination
     */
    total?: number;
}

/**
 * Check if a given object implements the WebPagination interface.
 */
export function instanceOfWebPagination(value: object): value is WebPagination {
    return true;
}

export function WebPaginationFromJSON(json: any): WebPagination {
    return WebPaginationFromJSONTyped(json, false);
}

export function WebPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function WebPaginationToJSON(json: any): WebPagination {
    return WebPaginationToJSONTyped(json, false);
}

export function WebPaginationToJSONTyped(value?: WebPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

