/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebRole
 */
export interface WebRole {
    /**
     * 
     * @type {WebRoleCodeEnum}
     * @memberof WebRole
     */
    code?: WebRoleCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebRole
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof WebRole
     */
    name?: string;
}


/**
 * @export
 */
export const WebRoleCodeEnum = {
    Admin: 'admin',
    Manager: 'manager',
    User: 'user'
} as const;
export type WebRoleCodeEnum = typeof WebRoleCodeEnum[keyof typeof WebRoleCodeEnum];


/**
 * Check if a given object implements the WebRole interface.
 */
export function instanceOfWebRole(value: object): value is WebRole {
    return true;
}

export function WebRoleFromJSON(json: any): WebRole {
    return WebRoleFromJSONTyped(json, false);
}

export function WebRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebRole {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function WebRoleToJSON(json: any): WebRole {
    return WebRoleToJSONTyped(json, false);
}

export function WebRoleToJSONTyped(value?: WebRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'name': value['name'],
    };
}

