/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebStatus
 */
export interface WebStatus {
    /**
     * 
     * @type {string}
     * @memberof WebStatus
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof WebStatus
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof WebStatus
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof WebStatus
     */
    isFinal: boolean;
    /**
     * 
     * @type {string}
     * @memberof WebStatus
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WebStatus
     */
    sort: number;
}

/**
 * Check if a given object implements the WebStatus interface.
 */
export function instanceOfWebStatus(value: object): value is WebStatus {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isFinal' in value) || value['isFinal'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function WebStatusFromJSON(json: any): WebStatus {
    return WebStatusFromJSONTyped(json, false);
}

export function WebStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
        'id': json['id'],
        'isFinal': json['isFinal'],
        'name': json['name'],
        'sort': json['sort'],
    };
}

export function WebStatusToJSON(json: any): WebStatus {
    return WebStatusToJSONTyped(json, false);
}

export function WebStatusToJSONTyped(value?: WebStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'id': value['id'],
        'isFinal': value['isFinal'],
        'name': value['name'],
        'sort': value['sort'],
    };
}

