/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebTeam
 */
export interface WebTeam {
    /**
     * 
     * @type {string}
     * @memberof WebTeam
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof WebTeam
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof WebTeam
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof WebTeam
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WebTeam
     */
    sort: number;
}

/**
 * Check if a given object implements the WebTeam interface.
 */
export function instanceOfWebTeam(value: object): value is WebTeam {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function WebTeamFromJSON(json: any): WebTeam {
    return WebTeamFromJSONTyped(json, false);
}

export function WebTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebTeam {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
        'id': json['id'],
        'name': json['name'],
        'sort': json['sort'],
    };
}

export function WebTeamToJSON(json: any): WebTeam {
    return WebTeamToJSONTyped(json, false);
}

export function WebTeamToJSONTyped(value?: WebTeam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'sort': value['sort'],
    };
}

