/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebUpdatePriorityRequest
 */
export interface WebUpdatePriorityRequest {
    /**
     * 
     * @type {string}
     * @memberof WebUpdatePriorityRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof WebUpdatePriorityRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof WebUpdatePriorityRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WebUpdatePriorityRequest
     */
    sort: number;
}

/**
 * Check if a given object implements the WebUpdatePriorityRequest interface.
 */
export function instanceOfWebUpdatePriorityRequest(value: object): value is WebUpdatePriorityRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function WebUpdatePriorityRequestFromJSON(json: any): WebUpdatePriorityRequest {
    return WebUpdatePriorityRequestFromJSONTyped(json, false);
}

export function WebUpdatePriorityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebUpdatePriorityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
        'name': json['name'],
        'sort': json['sort'],
    };
}

export function WebUpdatePriorityRequestToJSON(json: any): WebUpdatePriorityRequest {
    return WebUpdatePriorityRequestToJSONTyped(json, false);
}

export function WebUpdatePriorityRequestToJSONTyped(value?: WebUpdatePriorityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'name': value['name'],
        'sort': value['sort'],
    };
}

