/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebUpdateUserRequest
 */
export interface WebUpdateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof WebUpdateUserRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof WebUpdateUserRequest
     */
    password?: string;
    /**
     * 
     * @type {WebUpdateUserRequestRoleEnum}
     * @memberof WebUpdateUserRequest
     */
    role?: WebUpdateUserRequestRoleEnum;
    /**
     * 
     * @type {number}
     * @memberof WebUpdateUserRequest
     */
    teamId?: number;
    /**
     * 
     * @type {string}
     * @memberof WebUpdateUserRequest
     */
    username?: string;
}


/**
 * @export
 */
export const WebUpdateUserRequestRoleEnum = {
    Admin: 'admin',
    Manager: 'manager',
    User: 'user'
} as const;
export type WebUpdateUserRequestRoleEnum = typeof WebUpdateUserRequestRoleEnum[keyof typeof WebUpdateUserRequestRoleEnum];


/**
 * Check if a given object implements the WebUpdateUserRequest interface.
 */
export function instanceOfWebUpdateUserRequest(value: object): value is WebUpdateUserRequest {
    return true;
}

export function WebUpdateUserRequestFromJSON(json: any): WebUpdateUserRequest {
    return WebUpdateUserRequestFromJSONTyped(json, false);
}

export function WebUpdateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebUpdateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'role': json['role'] == null ? undefined : json['role'],
        'teamId': json['teamId'] == null ? undefined : json['teamId'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function WebUpdateUserRequestToJSON(json: any): WebUpdateUserRequest {
    return WebUpdateUserRequestToJSONTyped(json, false);
}

export function WebUpdateUserRequestToJSONTyped(value?: WebUpdateUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'role': value['role'],
        'teamId': value['teamId'],
        'username': value['username'],
    };
}

