/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebUpdateIncidentRequest
 */
export interface WebUpdateIncidentRequest {
    /**
     * 
     * @type {string}
     * @memberof WebUpdateIncidentRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof WebUpdateIncidentRequest
     */
    priorityId?: number;
    /**
     * 
     * @type {number}
     * @memberof WebUpdateIncidentRequest
     */
    statusId?: number;
    /**
     * 
     * @type {string}
     * @memberof WebUpdateIncidentRequest
     */
    title?: string;
}

/**
 * Check if a given object implements the WebUpdateIncidentRequest interface.
 */
export function instanceOfWebUpdateIncidentRequest(value: object): value is WebUpdateIncidentRequest {
    return true;
}

export function WebUpdateIncidentRequestFromJSON(json: any): WebUpdateIncidentRequest {
    return WebUpdateIncidentRequestFromJSONTyped(json, false);
}

export function WebUpdateIncidentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebUpdateIncidentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'priorityId': json['priorityId'] == null ? undefined : json['priorityId'],
        'statusId': json['statusId'] == null ? undefined : json['statusId'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function WebUpdateIncidentRequestToJSON(json: any): WebUpdateIncidentRequest {
    return WebUpdateIncidentRequestToJSONTyped(json, false);
}

export function WebUpdateIncidentRequestToJSONTyped(value?: WebUpdateIncidentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'priorityId': value['priorityId'],
        'statusId': value['statusId'],
        'title': value['title'],
    };
}

