/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebUpdateStatusRequest
 */
export interface WebUpdateStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof WebUpdateStatusRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof WebUpdateStatusRequest
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebUpdateStatusRequest
     */
    isFinal: boolean;
    /**
     * 
     * @type {string}
     * @memberof WebUpdateStatusRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WebUpdateStatusRequest
     */
    sort: number;
}

/**
 * Check if a given object implements the WebUpdateStatusRequest interface.
 */
export function instanceOfWebUpdateStatusRequest(value: object): value is WebUpdateStatusRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('isFinal' in value) || value['isFinal'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function WebUpdateStatusRequestFromJSON(json: any): WebUpdateStatusRequest {
    return WebUpdateStatusRequestFromJSONTyped(json, false);
}

export function WebUpdateStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebUpdateStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
        'isFinal': json['isFinal'],
        'name': json['name'],
        'sort': json['sort'],
    };
}

export function WebUpdateStatusRequestToJSON(json: any): WebUpdateStatusRequest {
    return WebUpdateStatusRequestToJSONTyped(json, false);
}

export function WebUpdateStatusRequestToJSONTyped(value?: WebUpdateStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'isFinal': value['isFinal'],
        'name': value['name'],
        'sort': value['sort'],
    };
}

