/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebUpdateDictEntityRequest
 */
export interface WebUpdateDictEntityRequest {
    /**
     * 
     * @type {string}
     * @memberof WebUpdateDictEntityRequest
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof WebUpdateDictEntityRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof WebUpdateDictEntityRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WebUpdateDictEntityRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the WebUpdateDictEntityRequest interface.
 */
export function instanceOfWebUpdateDictEntityRequest(value: object): value is WebUpdateDictEntityRequest {
    return true;
}

export function WebUpdateDictEntityRequestFromJSON(json: any): WebUpdateDictEntityRequest {
    return WebUpdateDictEntityRequestFromJSONTyped(json, false);
}

export function WebUpdateDictEntityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebUpdateDictEntityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function WebUpdateDictEntityRequestToJSON(json: any): WebUpdateDictEntityRequest {
    return WebUpdateDictEntityRequestToJSONTyped(json, false);
}

export function WebUpdateDictEntityRequestToJSONTyped(value?: WebUpdateDictEntityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
    };
}

