/* tslint:disable */
/* eslint-disable */
/**
 * Fixik API
 * Incident management system API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebUserResponse
 */
export interface WebUserResponse {
    /**
     * 
     * @type {string}
     * @memberof WebUserResponse
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof WebUserResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof WebUserResponse
     */
    name: string;
    /**
     * 
     * @type {WebUserResponseRoleEnum}
     * @memberof WebUserResponse
     */
    role: WebUserResponseRoleEnum;
    /**
     * 
     * @type {number}
     * @memberof WebUserResponse
     */
    teamId?: number;
    /**
     * 
     * @type {string}
     * @memberof WebUserResponse
     */
    username: string;
}


/**
 * @export
 */
export const WebUserResponseRoleEnum = {
    Admin: 'admin',
    Manager: 'manager',
    User: 'user'
} as const;
export type WebUserResponseRoleEnum = typeof WebUserResponseRoleEnum[keyof typeof WebUserResponseRoleEnum];


/**
 * Check if a given object implements the WebUserResponse interface.
 */
export function instanceOfWebUserResponse(value: object): value is WebUserResponse {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function WebUserResponseFromJSON(json: any): WebUserResponse {
    return WebUserResponseFromJSONTyped(json, false);
}

export function WebUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'id': json['id'],
        'name': json['name'],
        'role': json['role'],
        'teamId': json['teamId'] == null ? undefined : json['teamId'],
        'username': json['username'],
    };
}

export function WebUserResponseToJSON(json: any): WebUserResponse {
    return WebUserResponseToJSONTyped(json, false);
}

export function WebUserResponseToJSONTyped(value?: WebUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'id': value['id'],
        'name': value['name'],
        'role': value['role'],
        'teamId': value['teamId'],
        'username': value['username'],
    };
}

