export const PERMISSIONS = {
  INCIDENT_GET: 'INCIDENT_GET',
  INCIDENT_CREATE: 'INCIDENT_CREATE',
  INCIDENT_UPDATE: 'INCIDENT_UPDATE',
  INCIDENT_DELETE: 'INCIDENT_DELETE',

  COMMENT_GET: 'COMMENT_GET',
  COMMENT_CREATE: 'COMMENT_CREATE',
  COMMENT_UPDATE: 'COMMENT_UPDATE',
  COMMENT_DELETE: 'COMMENT_DELETE',

  USER_GET: 'USER_GET',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  TEAM_GET: 'TEAM_GET',
  TEAM_CREATE: 'TEAM_CREATE',
  TEAM_UPDATE: 'TEAM_UPDATE',
  TEAM_DELETE: 'TEAM_DELETE',

  PRIORITY_GET: 'PRIORITY_GET',
  PRIORITY_CREATE: 'PRIORITY_CREATE',
  PRIORITY_UPDATE: 'PRIORITY_UPDATE',
  PRIORITY_DELETE: 'PRIORITY_DELETE',

  STATUS_GET: 'STATUS_GET',
  STATUS_CREATE: 'STATUS_CREATE',
  STATUS_UPDATE: 'STATUS_UPDATE',
  STATUS_DELETE: 'STATUS_DELETE',
} as const

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
